### PR TITLE
Build/ update broccoli-replace to 2.0.2

### PR DESCRIPTION
**Pull request by BlueCutOfficial**
### Update broccoli-replace to 2.0.2
`broccoli-replace` has been updated from 0.12.0 to 2.0.2. This version contains an update of `applause` and `lodash` dependencies. 
Also, yarn-deduplicate command has been launched.

### CODE REVIEW

**Comment by mraustinmiller** [comment]
Would love to have this updated 👍

**Comment by andybluntish** [comment]
Hey, sorry for the delay.

I have been working on an upgrade to the Ember CLI version, which ended up as a re-write of how the replacements are done. We now use [outaTiME/applause](https://github.com/outaTiME/applause) directly, instead of via [broccoli-replace](https://github.com/outaTiME/broccoli-replace). This was mainly done to get compatibility with the Embroider tests, but will also hopefully mean less indirection with dependencies, and easier maintenance.

I've just published this as [v2.0.0](https://github.com/andybluntish/ember-cli-replace/releases/tag/v2.0.0) since there are potentially breaking changes related to how the file paths are specified (but it should be a very easy upgrade).

Hopefully this will also solve the issues you were having with the out-of-date version of broccoli-replace.

**Comment by andybluntish** [comment]
This change is no longer relevant now v2 doesn't use broccoli-replace.

**Comment by mraustinmiller** [comment]
> Hey, sorry for the delay.
> 
> 
> 
> I have been working on an upgrade to the Ember CLI version, which ended up as a re-write of how the replacements are done. We now use [outaTiME/applause](https://github.com/outaTiME/applause) directly, instead of via [broccoli-replace](https://github.com/outaTiME/broccoli-replace). This was mainly done to get compatibility with the Embroider tests, but will also hopefully mean less indirection with dependencies, and easier maintenance.
> 
> 
> 
> I've just published this as [v2.0.0](https://github.com/andybluntish/ember-cli-replace/releases/tag/v2.0.0) since there are potentially breaking changes related to how the file paths are specified (but it should be a very easy upgrade).
> 
> 
> 
> Hopefully this will also solve the issues you were having with the out-of-date version of broccoli-replace.

That is awesome. Thank you much Andy!

**Pull request closed without merging**
